# Generated by Django 4.2.2 on 2023-07-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_delete_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='name',
            field=models.TextField(max_length=200, unique=True),
        ),
    ]
