# Generated by Django 4.2.2 on 2023-07-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_todolist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Complete',
            field=models.BooleanField(default=False),
        ),
    ]
